version: '3.5'
services:
  api:
    image: kalatea-base-api
    env_file: .env.test
    build:
      context: .
      target: build
      args:
        - AUTH_REPO_ACCESS_KEY
    command: npm run test
    environment:
      - APP_ENV=testing
      - MYSQL_DB_TEST=$MYSQL_DB_TEST
      - MYSQL_PORT_TEST=$MYSQL_PORT_TEST
      - MYSQL_HOST_TEST=mysqldb
      - MYSQL_USER_TEST=$MYSQL_USER_TEST
      - APP_PORT=5555
      - AWS_ENDPOINT=http://s3:9000
    depends_on:
      - mysqldb
    ports:
      - "4445:4445"
  mysqldb:
    image: mysql
    env_file: .env.test
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_PASSWORD
      MYSQL_DATABASE: $MYSQL_DB
    ports:
      - '$MYSQL_PORT:$MYSQL_PORT'
  s3:
    image: minio/minio
    env_file: .env.test
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: $AWS_KEY
      MINIO_ROOT_PASSWORD: $AWS_SECRET
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - "$MINIO_VOLUME_MOUNT:/data"

